#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# finish — clear, then close out the run.
finish() {
  _clear
  printf '\n%s%s  ✓ Verification run complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

REPO_ROOT=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
DOC_FILE="$REPO_ROOT/docs/HARDWARE_VERIFICATION.md"
UTC_STAMP=$(/bin/date -u +%Y%m%dT%H%M%SZ)
RUN_DATE=$(/bin/date -u +%Y-%m-%d)
LABEL="se-sshctl-bio-${UTC_STAMP}-$$"
RUN_DIR=$(mktemp -d "${TMPDIR:-/tmp}/se-sshctl-bio.XXXXXX")
REPORT_FILE="${REPORT_FILE:-$RUN_DIR/HARDWARE_VERIFICATION_APPEND.md}"
/bin/chmod 700 "$RUN_DIR"

SSHCTL="$REPO_ROOT/.build/release/se-sshctl"
LOCAL_USER=$(/usr/bin/id -un)
CTK_SHA256=""
IDENTITY_FILE="$RUN_DIR/id_ecdsa_sk_rk"
IDENTITY_CREATED=0
CLEANED_UP=0
CURRENT_STAGE=preflight
TOUCH_ID_CREATE=no
TOUCH_ID_INSTALL=no
TOUCH_ID_LOCAL=no
REMOTE_RESULT=not-run
TOUCH_ID_REMOTE=not-run
AUTHORIZATION_CHANGED=0
AUTHORIZED_KEYS="$HOME/.ssh/authorized_keys"
AUTHORIZED_KEYS_BACKUP="$RUN_DIR/authorized_keys.before"
AUTHORIZED_KEYS_EXISTED=0
SSH_DIRECTORY_CREATED=0

restore_authorization() {
  (( AUTHORIZATION_CHANGED )) || return 0
  if (( AUTHORIZED_KEYS_EXISTED )); then
    /bin/cp -fp "$AUTHORIZED_KEYS_BACKUP" "$AUTHORIZED_KEYS"
    /usr/bin/cmp -s "$AUTHORIZED_KEYS_BACKUP" "$AUTHORIZED_KEYS" || return 1
  else
    /bin/rm -f "$AUTHORIZED_KEYS"
    if (( SSH_DIRECTORY_CREATED )); then /bin/rmdir "$HOME/.ssh" 2>/dev/null || true; fi
  fi
  AUTHORIZATION_CHANGED=0
}

on_exit() {
  local status=$?
  trap - EXIT
  if ! restore_authorization; then
    printf '\n%s%s  WARNING: failed to restore %s%s\n' "$BOLD" "$RED" "$AUTHORIZED_KEYS" "$RESET"
    status=1
  fi
  if (( IDENTITY_CREATED )) && (( ! CLEANED_UP )); then
    printf '\n%s%s  Test identity still exists%s\n' "$BOLD" "$YELLOW" "$RESET"
    if [[ -n "$CTK_SHA256" ]]; then
      printf '  Find its sc_auth SHA-1 hash and delete it with:\n'
      printf '  %q identity list -t sha1\n  /usr/sbin/sc_auth delete-ctk-identity -h SHA1\n' "$SSHCTL"
      printf '  Its CTK SHA-256 hash is %s\n' "$CTK_SHA256"
    else
      printf '  Find its SHA-256 hash by label %q:\n  %q identity list\n' "$LABEL" "$SSHCTL"
    fi
    printf '  Temporary identity-file directory: %s\n' "$RUN_DIR"
  elif (( status != 0 )); then
    printf '\n  Failed during stage: %s\n' "$CURRENT_STAGE"
  fi
  exit "$status"
}
trap on_exit EXIT

banner "se-sshctl MacBook Air Touch ID verification"

CURRENT_STAGE=preflight
stage "Build and inspect this Mac"
say "This wizard builds the current checkout and records only non-secret hardware metadata."
[[ "$(/usr/bin/uname -m)" == "arm64" ]] || { warn "Apple silicon is required"; exit 1; }
HARDWARE=$(/usr/sbin/system_profiler SPHardwareDataType -detailLevel mini)
MODEL_NAME=$(printf '%s\n' "$HARDWARE" | /usr/bin/awk -F': ' '/Model Name/{print $2; exit}')
MODEL_IDENTIFIER=$(printf '%s\n' "$HARDWARE" | /usr/bin/awk -F': ' '/Model Identifier/{print $2; exit}')
CHIP=$(printf '%s\n' "$HARDWARE" | /usr/bin/awk -F': ' '/Chip/{print $2; exit}')
[[ "$MODEL_NAME" == "MacBook Air" ]] || { warn "this run is reserved for MacBook Air hardware"; exit 1; }
step "Confirm Touch ID is enrolled for the current macOS account."
confirm "Is Touch ID available and enrolled on this MacBook Air?" || exit 1
(
  cd "$REPO_ROOT"
  /usr/bin/swift build --configuration release
)
[[ -x "$SSHCTL" ]] || { warn "release build did not produce se-sshctl"; exit 1; }
DOCTOR_JSON="$RUN_DIR/doctor.json"
"$SSHCTL" doctor --json > "$DOCTOR_JSON"
[[ "$(/usr/bin/plutil -extract provider.signatureValid raw -o - "$DOCTOR_JSON")" == "true" ]] || {
  warn "the SSH provider signature is not valid"; exit 1;
}
[[ "$(/usr/bin/plutil -extract provider.appleAnchored raw -o - "$DOCTOR_JSON")" == "true" ]] || {
  warn "the SSH provider is not Apple-anchored"; exit 1;
}
[[ "$(/usr/bin/plutil -extract scAuth.available raw -o - "$DOCTOR_JSON")" == "true" ]] || {
  warn "sc_auth is unavailable"; exit 1;
}
MACOS_VERSION=$(/usr/bin/plutil -extract platform.version raw -o - "$DOCTOR_JSON")
MACOS_BUILD=$(/usr/bin/plutil -extract platform.build raw -o - "$DOCTOR_JSON")
OPENSSH_VERSION=$(/usr/bin/plutil -extract openSSH.version raw -o - "$DOCTOR_JSON")
SOURCE_REVISION=$(cd "$REPO_ROOT" && /usr/bin/git describe --always --dirty)
say "Current source and Apple provider checks passed."

CURRENT_STAGE=identity_create
stage "Create a bio test identity"
say "A persistent p-256-ne + bio identity named $LABEL will be created and later deleted."
warn "If the wizard stops before cleanup, it prints the exact deletion command."
confirm "Create this test identity now?" || {
  CLEANED_UP=1
  /bin/rm -rf "$RUN_DIR"
  finish
  exit 0
}
CREATE_JSON="$RUN_DIR/create.json"
IDENTITY_CREATED=1
"$SSHCTL" identity create -l "$LABEL" -k p-256-ne -t bio --json > "$CREATE_JSON"
CTK_SHA256=$(/usr/bin/plutil -extract identity.ctkPublicKeyHash raw -o - "$CREATE_JSON")
[[ "$CTK_SHA256" =~ ^[0-9A-Fa-f]{64}$ ]] || { warn "creation returned an invalid CTK SHA-256 hash"; exit 1; }
if confirm "Did macOS request and accept Touch ID during creation?"; then TOUCH_ID_CREATE=yes; fi
say "Exactly one bio identity was created. Its hash is not written to the report."

CURRENT_STAGE=identity_file_install
stage "Install a temporary identity file"
say "The identity file is confined to $RUN_DIR."
step "At both passphrase prompts, press Enter. This keeps the later BatchMode remote probe usable."
IDENTITY_FILE_JSON="$RUN_DIR/identity-file.json"
"$SSHCTL" install --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" --json > "$IDENTITY_FILE_JSON"
[[ "$(/usr/bin/plutil -extract status raw -o - "$IDENTITY_FILE_JSON")" == "installed" ]] || {
  warn "identity-file installation did not report success"; exit 1;
}
[[ -f "$IDENTITY_FILE" && -f "$IDENTITY_FILE.pub" ]] || { warn "identity files are missing"; exit 1; }
if confirm "Did macOS request and accept Touch ID during installation?"; then TOUCH_ID_INSTALL=yes; fi
say "The temporary identity file matches the selected CTK identity."

CURRENT_STAGE=local_sign_verify
stage "Verify a Touch ID-backed signature"
say "The CLI will sign and verify a temporary challenge through Apple's provider."
VERIFY_JSON="$RUN_DIR/verify.json"
"$SSHCTL" verify local --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" --json > "$VERIFY_JSON"
[[ "$(/usr/bin/plutil -extract status raw -o - "$VERIFY_JSON")" == "passed" ]] || {
  warn "local verification did not pass"; exit 1;
}
if confirm "Did you approve a Touch ID prompt during signing?"; then TOUCH_ID_LOCAL=yes; fi
say "Provider-backed signing and cryptographic verification passed."

CURRENT_STAGE=remote_verify
stage "Optionally verify localhost SSH authentication"
say "This optional probe temporarily appends the test public key to ~/.ssh/authorized_keys."
say "The original file is restored byte-for-byte immediately after the probe."
if confirm "Run the localhost SSH authentication probe?"; then
  [[ ! -L "$AUTHORIZED_KEYS" ]] || { warn "authorized_keys is a symlink; refusing to modify it"; exit 1; }
  if ! /usr/bin/ssh-keygen -F localhost >/dev/null; then
    warn "localhost is not in known_hosts; establish and verify that host key before rerunning"
    exit 1
  fi
  if [[ ! -d "$HOME/.ssh" ]]; then
    /bin/mkdir -m 700 "$HOME/.ssh"
    SSH_DIRECTORY_CREATED=1
  fi
  if [[ -f "$AUTHORIZED_KEYS" ]]; then
    /bin/cp -fp "$AUTHORIZED_KEYS" "$AUTHORIZED_KEYS_BACKUP"
    AUTHORIZED_KEYS_EXISTED=1
  else
    : > "$AUTHORIZED_KEYS"
    /bin/chmod 600 "$AUTHORIZED_KEYS"
  fi
  AUTHORIZATION_CHANGED=1
  PUBLIC_KEY=$(/bin/cat "$IDENTITY_FILE.pub")
  printf '\nrestrict %s se-sshctl-touch-id-verification\n' "$PUBLIC_KEY" >> "$AUTHORIZED_KEYS"
  /bin/chmod 600 "$AUTHORIZED_KEYS"
  REMOTE_JSON="$RUN_DIR/remote.json"
  "$SSHCTL" verify remote \
    --ctk-sha256 "$CTK_SHA256" \
    --identity-file "$IDENTITY_FILE" \
    --target "$LOCAL_USER@localhost" \
    --json > "$REMOTE_JSON"
  [[ "$(/usr/bin/plutil -extract status raw -o - "$REMOTE_JSON")" == "passed" ]] || {
    warn "remote verification did not pass"; exit 1;
  }
  REMOTE_RESULT=passed
  if confirm "Did you approve a Touch ID prompt during SSH authentication?"; then TOUCH_ID_REMOTE=yes; else TOUCH_ID_REMOTE=no; fi
  restore_authorization || { warn "authorized_keys restoration failed"; exit 1; }
  say "Localhost authentication passed and authorized_keys was restored."
else
  note "Remote verification recorded as not-run."
fi

CURRENT_STAGE=cleanup
stage "Delete the test identity"
say "se-sshctl does not delete identities; this uses Apple's sc_auth directly."
warn "The next action permanently deletes only the test identity named $LABEL."
confirm "Delete the test identity and temporary identity file now?" || {
  warn "Cleanup is required before a run can be recorded"; exit 1;
}
LIST_SHA1_JSON="$RUN_DIR/list-sha1.json"
"$SSHCTL" identity list -t sha1 --json > "$LIST_SHA1_JSON"
CTK_SHA1=""
index=0
while entry_label=$(/usr/bin/plutil -extract "identities.$index.label" raw -o - "$LIST_SHA1_JSON" 2>/dev/null); do
  if [[ "$entry_label" == "$LABEL" ]]; then
    [[ -z "$CTK_SHA1" ]] || { warn "label $LABEL matches more than one identity; refusing to guess"; exit 1; }
    CTK_SHA1=$(/usr/bin/plutil -extract "identities.$index.ctkPublicKeyHash" raw -o - "$LIST_SHA1_JSON")
  fi
  index=$(( index + 1 ))
done
[[ "$CTK_SHA1" =~ ^[0-9A-Fa-f]{40}$ ]] || { warn "could not resolve the sc_auth SHA-1 hash for $LABEL"; exit 1; }
/usr/sbin/sc_auth delete-ctk-identity -h "$CTK_SHA1" || { warn "sc_auth deletion failed"; exit 1; }
LIST_AFTER_JSON="$RUN_DIR/list-after.json"
"$SSHCTL" identity list --json > "$LIST_AFTER_JSON"
/usr/bin/grep -qi -- "$CTK_SHA256" "$LIST_AFTER_JSON" && {
  warn "sc_auth reported success but the identity is still present"; exit 1;
}
IDENTITY_CREATED=0
CLEANED_UP=1
say "The test identity was deleted and local authorization is restored."

CURRENT_STAGE=record
stage "Append the verified run"
{
  printf '\n## MacBook Air Touch ID verification — %s\n\n' "$RUN_DATE"
  printf 'Verified on physical Touch ID hardware:\n\n'
  printf '```text\n'
  printf 'model:     %s (%s)\n' "$MODEL_NAME" "$MODEL_IDENTIFIER"
  printf 'chip:      %s\n' "$CHIP"
  printf 'macOS:     %s (%s)\n' "$MACOS_VERSION" "$MACOS_BUILD"
  printf 'OpenSSH:   %s\n' "$OPENSSH_VERSION"
  printf 'provider:  /usr/lib/ssh-keychain.dylib, Apple-anchored signature verified\n'
  printf 'source:    %s\n' "$SOURCE_REVISION"
  printf 'params:    -k p-256-ne -t bio\n'
  printf '```\n\n'
  printf 'The wizard recorded:\n\n'
  printf -- '- identity creation: passed; Touch ID prompt observed: %s;\n' "$TOUCH_ID_CREATE"
  printf -- '- identity-file installation with an empty passphrase: passed; Touch ID prompt observed: %s;\n' "$TOUCH_ID_INSTALL"
  printf -- '- local provider-backed signing and signature verification: passed; Touch ID prompt observed: %s;\n' "$TOUCH_ID_LOCAL"
  printf -- '- localhost authentication: %s; Touch ID prompt observed: %s;\n' "$REMOTE_RESULT" "$TOUCH_ID_REMOTE"
  printf -- '- the temporary CTK identity was deleted and local authorization was restored.\n\n'
  printf 'This run covers an unlocked GUI session. It does not prove behavior while the console is locked, logged out, before first unlock after reboot, or under launchd.\n'
} > "$REPORT_FILE"

if [[ "$TOUCH_ID_LOCAL" != "yes" ]]; then
  warn "Local signing passed, but no Touch ID approval was observed; the run is inconclusive."
  PENDING_REPORT="${TMPDIR:-/tmp}/se-sshctl-bio-${UTC_STAMP}.md"
  /bin/cp -f "$REPORT_FILE" "$PENDING_REPORT"
  /bin/rm -rf "$RUN_DIR"
  say "Review the unappended record at $PENDING_REPORT"
  exit 1
fi
if confirm "Append this run to docs/HARDWARE_VERIFICATION.md?"; then
  /bin/cat "$REPORT_FILE" >> "$DOC_FILE"
  say "Appended one verified run to $DOC_FILE"
else
  PENDING_REPORT="${TMPDIR:-/tmp}/se-sshctl-bio-${UTC_STAMP}.md"
  /bin/cp -f "$REPORT_FILE" "$PENDING_REPORT"
  say "Not appended. Review the generated record at $PENDING_REPORT"
fi
/bin/rm -rf "$RUN_DIR"

finish
