#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard tells you exactly what to do on this Mac and records what\n' "$DIM"
  printf '  it observes. Stop any time with Ctrl-C; anything it created is reported\n'
  printf '  so you can clean up by hand.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# finish — clear, then close out the run.
finish() {
  _clear
  printf '\n%s%s  ✓ Verification run complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one context per invocation. State persists between runs so the
# sequence can span a lock, a logout, and a reboot.

TOTAL_STAGES=5

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SSHCTL="$REPO_ROOT/.build/release/se-sshctl"
STATE_DIR="$HOME/.se-sshctl-none-verification"
STATE_FILE="$STATE_DIR/state.env"
IDENTITY_FILE="$STATE_DIR/id_ecdsa_sk_rk"
AUTHORIZED_KEYS="$HOME/.ssh/authorized_keys"
AUTHORIZED_KEYS_BACKUP="$STATE_DIR/authorized_keys.before"
LABEL="se-sshctl-none-remote-verification"
REPORT_TARGET="$REPO_ROOT/docs/HARDWARE_VERIFICATION.md"
CURRENT_STAGE=start

CONTEXT="${1:-}"
case "$CONTEXT" in
  unlocked|locked|logged-out|pre-first-unlock|report) ;;
  *)
    cat >&2 <<USAGE
usage: ${BASH_SOURCE[0]##*/} <context>

Measures whether a '-t none' Secure Enclave identity can sign and authenticate
from an SSH session when no one is at the Mac. That is the situation '-t none'
exists for, and it is the one nobody has verified.

WHAT EACH RUN ACTUALLY DOES

  It runs on the Mac that holds the identity — the SSH target, not the machine
  you are typing on — and in each context it performs two real operations:

    ssh-keygen -Y sign through /usr/lib/ssh-keychain.dylib, which asks the
      Secure Enclave for a signature and verifies it against the public key;

    a full public-key SSH authentication to USER@localhost using only the
      installed identity file, with ssh-agent, ~/.ssh/config, host-based,
      password, and keyboard-interactive authentication all disabled, so the
      only way it can succeed is a fresh signature from the enclave.

  localhost is the target on purpose: it removes the network and a remote
  sshd policy as variables, leaving exactly the question being asked — can the
  enclave sign when no GUI session is attached to this Mac?

  What it does not cover: launchd or other sessionless daemon contexts, a
  network SSH target with its own server policy, and the '-t bio' path, which
  is scripts/verify-bio.sh.

Run this over SSH, once per context, IN THIS ORDER. The first context creates
the test identity; every later one reuses it and will refuse to create one, so
that a setup failure in a degraded context is never mistaken for a measurement:

  unlocked          a normal SSH session while the GUI session is unlocked
  locked            lock the console (Ctrl-Cmd-Q), then reconnect and run
  logged-out        log out of the GUI entirely, then reconnect and run
  pre-first-unlock  reboot, do not touch the login window, reconnect and run
  report            append the aggregate to docs/HARDWARE_VERIFICATION.md and clean up

State lives in $HOME/.se-sshctl-none-verification so it survives the reboot.
Nothing is cleaned up until you run 'report', because the identity has to
outlive each context. A failing context is a result, not an error: record it
and continue to the next one.
USAGE
    exit 2
    ;;
esac

# ──────────────────────────────────────────────────────────────────────────

# shellcheck disable=SC1090  # the state file is written by save_state below
load_state() { [[ -f "$STATE_FILE" ]] && . "$STATE_FILE" || true; }

save_state() {
  local key="$1" value="$2" tmp
  tmp=$(/usr/bin/mktemp "$STATE_DIR/state.XXXXXX")
  if [[ -f "$STATE_FILE" ]]; then /usr/bin/grep -vE "^${key}=" "$STATE_FILE" > "$tmp" || true; fi
  printf '%s=%q\n' "$key" "$value" >> "$tmp"
  /bin/mv -f "$tmp" "$STATE_FILE"
  /bin/chmod 600 "$STATE_FILE"
}

on_exit() {
  local status=$?
  trap - EXIT
  if [[ "$CONTEXT" != "report" ]] && [[ -f "$STATE_FILE" ]]; then
    printf '\n%s%s  Cleanup is pending on purpose%s\n' "$BOLD" "$YELLOW" "$RESET"
    printf '  The test identity and its localhost authorization stay in place so the\n'
    printf '  next context can use them. Run this when you are done:\n'
    printf '    %q report\n' "${BASH_SOURCE[0]}"
  fi
  (( status == 0 )) || printf '\n  Failed during stage: %s\n' "$CURRENT_STAGE"
  exit "$status"
}
trap on_exit EXIT

/bin/mkdir -p "$STATE_DIR"
/bin/chmod 700 "$STATE_DIR"
load_state

banner "se-sshctl -t none remote-session verification · $CONTEXT"

# ── report ────────────────────────────────────────────────────────────────
if [[ "$CONTEXT" == "report" ]]; then
  TOTAL_STAGES=2
  CURRENT_STAGE=report
  stage "Write the aggregate"
  [[ -n "${CTK_SHA256:-}" ]] || { warn "no verification runs are recorded yet"; exit 1; }
  {
    printf '\n## -t none remote-session verification — %s\n\n' "$(/bin/date -u '+%Y-%m-%d')"
    printf 'Measured from an SSH session on physical hardware:\n\n'
    printf '```text\n'
    printf 'host:       %s\n' "${HOST_NAME:-unknown}"
    printf 'model:      %s (%s)\n' "${MODEL_NAME:-unknown}" "${MODEL_IDENTIFIER:-unknown}"
    printf 'chip:       %s\n' "${CHIP:-unknown}"
    printf 'macOS:      %s\n' "${MACOS_VERSION:-unknown}"
    printf 'OpenSSH:    %s\n' "${OPENSSH_VERSION:-unknown}"
    printf 'source:     %s\n' "${SOURCE_REVISION:-unknown}"
    printf 'params:     -k p-256-ne -t none --allow-unattended-signing\n'
    printf '```\n\n'
    printf '| Console state | local signing | localhost authentication |\n'
    printf '| --- | --- | --- |\n'
    for context in unlocked locked logged-out pre-first-unlock; do
      local_var="LOCAL_${context//-/_}"
      remote_var="REMOTE_${context//-/_}"
      printf '| %s | %s | %s |\n' "$context" "${!local_var:-not-run}" "${!remote_var:-not-run}"
    done
    for context in unlocked locked logged-out pre-first-unlock; do
      detail_var="DETAIL_${context//-/_}"
      [[ -n "${!detail_var:-}" ]] || continue
      printf '\n%s: %s\n' "$context" "${!detail_var}"
    done
    # shellcheck disable=SC2016  # the backticks are markdown, not a subshell
    printf '\nEach row is one SSH session into this Mac. "local signing" is\n'
    printf 'ssh-keygen -Y sign through the Apple provider; "localhost\n'
    printf 'authentication" is a real public-key SSH authentication using only\n'
    printf 'the Secure Enclave identity file, with the agent, user config, and\n'
    printf 'every password method disabled.\n'
    # shellcheck disable=SC2016  # the backticks are markdown, not a subshell
    printf '\nA `not-run` row was never attempted and says nothing about that context.\n'
  } >> "$REPORT_TARGET"
  say "Appended to $REPORT_TARGET."

  CURRENT_STAGE=cleanup
  stage "Remove the test identity and restore authorization"
  warn "This permanently deletes only the test identity named $LABEL."
  confirm "Delete it and restore $AUTHORIZED_KEYS now?" || { warn "cleanup skipped"; exit 1; }
  # Uses the tool's own deletion, which resolves the sc_auth SHA-1 locator,
  # verifies absence afterwards, and clears the identity file and verification
  # record. Deleting through raw sc_auth here would leave both behind.
  if "$SSHCTL" identity list --json | /usr/bin/grep -qi -- "$CTK_SHA256"; then
    "$SSHCTL" identity delete --ctk-sha256 "$CTK_SHA256" --confirm "$CTK_SHA256" \
      || { warn "deletion failed; delete it by hand with sc_auth delete-ctk-identity"; exit 1; }
  else
    note "the test identity is already gone"
    "$SSHCTL" manifest prune >/dev/null || true
  fi
  if [[ -f "$AUTHORIZED_KEYS_BACKUP" ]]; then
    /bin/cp -fp "$AUTHORIZED_KEYS_BACKUP" "$AUTHORIZED_KEYS"
  elif [[ "${AUTHORIZED_KEYS_CREATED:-0}" == "1" ]]; then
    /bin/rm -f "$AUTHORIZED_KEYS"
  fi
  /bin/rm -rf "$STATE_DIR"
  say "The test identity is gone and local authorization is restored."
  finish
  exit 0
fi

# ── preflight ─────────────────────────────────────────────────────────────
CURRENT_STAGE=preflight
stage "Check this session and build"
[[ "$(/usr/bin/uname -m)" == "arm64" ]] || { warn "Apple silicon is required"; exit 1; }
[[ -n "${SSH_CONNECTION:-}" ]] || {
  warn "run this over SSH; a local Terminal window is attached to the GUI session"
  warn "and would not prove anything about the contexts being measured"
  exit 1
}
(cd "$REPO_ROOT" && /usr/bin/swift build --configuration release)
[[ -x "$SSHCTL" ]] || { warn "release build did not produce se-sshctl"; exit 1; }
DOCTOR_JSON="$STATE_DIR/doctor.json"
"$SSHCTL" doctor --json > "$DOCTOR_JSON"
[[ "$(/usr/bin/plutil -extract provider.signatureValid raw -o - "$DOCTOR_JSON")" == "true" ]] || {
  warn "the SSH provider signature is not valid"; exit 1;
}
[[ "$(/usr/bin/plutil -extract provider.appleAnchored raw -o - "$DOCTOR_JSON")" == "true" ]] || {
  warn "the SSH provider is not Apple-anchored"; exit 1;
}
# Recorded per host: this wizard is meant to be run on whichever Mac can be
# locked, logged out, and rebooted, so a report that does not name its machine
# is not evidence about anything.
HARDWARE=$(/usr/sbin/system_profiler SPHardwareDataType -detailLevel mini)
save_state MODEL_NAME "$(printf '%s\n' "$HARDWARE" | /usr/bin/awk -F': ' '/Model Name/{print $2; exit}')"
save_state MODEL_IDENTIFIER "$(printf '%s\n' "$HARDWARE" | /usr/bin/awk -F': ' '/Model Identifier/{print $2; exit}')"
save_state CHIP "$(printf '%s\n' "$HARDWARE" | /usr/bin/awk -F': ' '/Chip/{print $2; exit}')"
save_state HOST_NAME "$(/usr/sbin/scutil --get LocalHostName 2>/dev/null || /bin/hostname -s)"
save_state MACOS_VERSION "$(/usr/bin/plutil -extract platform.version raw -o - "$DOCTOR_JSON")"
save_state OPENSSH_VERSION "$(/usr/bin/plutil -extract openSSH.version raw -o - "$DOCTOR_JSON")"
save_state SOURCE_REVISION "$(cd "$REPO_ROOT" && /usr/bin/git rev-parse HEAD)"
load_state

# ── console state ─────────────────────────────────────────────────────────
CURRENT_STAGE=console
stage "Check the console is in the '$CONTEXT' state"
# Checked, not asked. Every row of the report is labelled by this state, so a
# mis-answered prompt does not produce a missing result — it produces a wrong
# one, which is worse. macOS reports both facts we need.
CONSOLE_USER=$(/usr/bin/stat -f%Su /dev/console)
if /usr/sbin/ioreg -n Root -d1 -k CGSSessionScreenIsLocked | /usr/bin/grep -q CGSSessionScreenIsLocked; then
  SCREEN_LOCKED=1
else
  SCREEN_LOCKED=0
fi
note "console user: $CONSOLE_USER; screen locked: $([[ "$SCREEN_LOCKED" == 1 ]] && echo yes || echo no)"

require_state() {
  [[ "$1" == "$2" ]] && return 0
  warn "this Mac is not in the '$CONTEXT' state: $3"
  warn "put it in that state, reconnect over SSH, and run this again"
  exit 1
}

case "$CONTEXT" in
  unlocked)
    require_state "$([[ "$CONSOLE_USER" != "root" ]] && echo yes || echo no)" yes \
      "nobody is logged in at the console"
    require_state "$SCREEN_LOCKED" 0 "the screen is locked"
    say "Logged in at the console and unlocked. This is the baseline."
    ;;
  locked)
    require_state "$([[ "$CONSOLE_USER" != "root" ]] && echo yes || echo no)" yes \
      "nobody is logged in at the console, so this is logged-out, not locked"
    require_state "$SCREEN_LOCKED" 1 "the screen is not locked"
    say "Logged in at the console with the screen locked."
    ;;
  logged-out)
    require_state "$CONSOLE_USER" root "$CONSOLE_USER is still logged in at the console"
    say "No console session. Logged out of the GUI."
    ;;
  pre-first-unlock)
    require_state "$CONSOLE_USER" root "$CONSOLE_USER is logged in at the console"
    # Indistinguishable from logged-out by console state alone: both leave the
    # login window with no session. Whether a reboot happened with nobody
    # logging in since is the operator'"'"'s to attest.
    note "Booted $(/usr/bin/uptime | /usr/bin/sed -n '"'"'s/.*up \([^,]*\),.*/\1/p'"'"') ago."
    confirm "Has this Mac rebooted since anyone last logged in at the console?" \
      || { warn "reboot first, do not touch the login window, then run this"; exit 1; }
    ;;
esac

# ── identity ──────────────────────────────────────────────────────────────
CURRENT_STAGE=identity
stage "Reuse or create the test identity"
if [[ -n "${CTK_SHA256:-}" ]] && "$SSHCTL" identity list --json | /usr/bin/grep -qi -- "$CTK_SHA256"; then
  say "Reusing the identity created by an earlier context."
else
  # Creation is setup, not measurement, and it only happens in the baseline
  # context. Creating in a degraded context confuses a setup failure with a
  # result: if sc_auth cannot create or cannot enumerate while logged out,
  # that says nothing about whether an existing key can still sign.
  if [[ "$CONTEXT" != "unlocked" ]]; then
    warn "no test identity exists yet on this Mac"
    warn "run the baseline first, with the GUI session logged in and unlocked:"
    printf '    %q unlocked\n' "${BASH_SOURCE[0]}"
    warn "then return to '$CONTEXT'. Contexts after the baseline reuse that identity"
    warn "and never create one, so a creation failure cannot be mistaken for a result."
    exit 1
  fi
  warn "A persistent p-256-ne + none identity named $LABEL will be created."
  warn "-t none removes per-use approval: any process running as you can request"
  warn "signatures from it. That is exactly the property being measured."
  confirm "Create it now?" || exit 1
  CREATE_JSON="$STATE_DIR/create.json"
  "$SSHCTL" identity create -l "$LABEL" -k p-256-ne -t none --allow-unattended-signing --json > "$CREATE_JSON"
  CTK_SHA256=$(/usr/bin/plutil -extract identity.ctkPublicKeyHash raw -o - "$CREATE_JSON")
  [[ "$CTK_SHA256" =~ ^[0-9A-Fa-f]{64}$ ]] || { warn "creation returned an invalid hash"; exit 1; }
  save_state CTK_SHA256 "$CTK_SHA256"
  # --no-passphrase is what makes this possible at all: install used to demand a
  # controlling terminal, which a fully unattended context does not have.
  "$SSHCTL" install --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" --no-passphrase --json > "$STATE_DIR/install.json"
  if [[ -f "$AUTHORIZED_KEYS" ]]; then
    /bin/cp -fp "$AUTHORIZED_KEYS" "$AUTHORIZED_KEYS_BACKUP"
  else
    /bin/mkdir -p "$HOME/.ssh"; /bin/chmod 700 "$HOME/.ssh"
    save_state AUTHORIZED_KEYS_CREATED 1
  fi
  /bin/cat "$IDENTITY_FILE.pub" >> "$AUTHORIZED_KEYS"
  /bin/chmod 600 "$AUTHORIZED_KEYS"
  say "Created, installed, and authorized for localhost."
fi

# ── measure ───────────────────────────────────────────────────────────────
CURRENT_STAGE=measure
stage "Sign and authenticate from this session"
say "Neither command may show a GUI prompt. If one appears, that is the finding."
DETAIL=""
LOCAL_RESULT=failed
if "$SSHCTL" verify local --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" --json > "$STATE_DIR/local.json" 2>"$STATE_DIR/local.err"; then
  LOCAL_RESULT=passed
else
  warn "local signing failed in the '$CONTEXT' context — recording it"
  # "the enclave refused to sign" and "sc_auth could not even enumerate the
  # identity" are different findings, and only the reason distinguishes them.
  DETAIL=$(/usr/bin/tail -n 1 "$STATE_DIR/local.err")
  note "$DETAIL"
fi
REMOTE_RESULT=failed
if "$SSHCTL" verify remote --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" --target "$USER@localhost" --json > "$STATE_DIR/remote.json" 2>"$STATE_DIR/remote.err"; then
  REMOTE_RESULT=passed
else
  warn "localhost authentication failed in the '$CONTEXT' context — recording it"
  [[ -n "$DETAIL" ]] || DETAIL=$(/usr/bin/tail -n 1 "$STATE_DIR/remote.err")
  note "$(/usr/bin/tail -n 1 "$STATE_DIR/remote.err")"
fi
save_state "LOCAL_${CONTEXT//-/_}" "$LOCAL_RESULT"
save_state "REMOTE_${CONTEXT//-/_}" "$REMOTE_RESULT"
save_state "DETAIL_${CONTEXT//-/_}" "$DETAIL"

CURRENT_STAGE=summary
stage "Result for '$CONTEXT'"
# A failed context is a finding worth seeing at a glance, not an error.
result_line() {
  local colour="$GREEN"
  [[ "$2" == "passed" ]] || colour="$RED"
  printf '  %s %s%s%s\n' "$1" "$colour" "$2" "$RESET"
}
result_line "local signing:           " "$LOCAL_RESULT"
result_line "localhost authentication:" "$REMOTE_RESULT"
printf '\n'
case "$CONTEXT" in
  unlocked)         note "Next: lock the console, reconnect over SSH, run with 'locked'." ;;
  locked)           note "Next: log out of the GUI, reconnect over SSH, run with 'logged-out'." ;;
  logged-out)       note "Next: reboot, do not touch the login window, run with 'pre-first-unlock'." ;;
  pre-first-unlock) note "All four contexts are measured. Run with 'report' to write and clean up." ;;
esac
