#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard tells you exactly what to do on this Mac and records what\n' "$DIM"
  printf '  it observes. Stop any time with Ctrl-C; anything it created is reported\n'
  printf '  so you can clean up by hand.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# finish — clear, then close out the run.
finish() {
  _clear
  printf '\n%s%s  ✓ Verification run complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — a single experiment. It answers one open question and cleans up.

TOTAL_STAGES=7

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
SSHCTL="$REPO_ROOT/.build/release/se-sshctl"
RUN_DIR=$(/usr/bin/mktemp -d "${TMPDIR:-/tmp}/se-sshctl-cert-expiry.XXXXXX")
IDENTITY_FILE="$RUN_DIR/id_ecdsa_sk_rk"
AUTHORIZED_KEYS="$HOME/.ssh/authorized_keys"
AUTHORIZED_KEYS_BACKUP="$RUN_DIR/authorized_keys.before"
AUTHORIZED_KEYS_EXISTED=0
SSH_DIRECTORY_CREATED=0
AUTHORIZATION_CHANGED=0
LABEL="se-sshctl-cert-expiry-$$"
REPORT_TARGET="$REPO_ROOT/docs/HARDWARE_VERIFICATION.md"
IDENTITY_CREATED=0
CLEANED_UP=0
CTK_SHA256=""
CTK_SHA1=""
CURRENT_STAGE=start

BEFORE_LOCAL=not-run
BEFORE_REMOTE=not-run
AFTER_LOCAL=not-run
AFTER_REMOTE=not-run
AFTER_VALID_COLUMN=unknown
IMPORT_RESULT=not-run
REINSTALL_RESULT=not-run
REINSTALL_LOCAL=not-run

restore_authorization() {
  (( AUTHORIZATION_CHANGED )) || return 0
  if (( AUTHORIZED_KEYS_EXISTED )); then
    /bin/cp -fp "$AUTHORIZED_KEYS_BACKUP" "$AUTHORIZED_KEYS"
    /usr/bin/cmp -s "$AUTHORIZED_KEYS_BACKUP" "$AUTHORIZED_KEYS" || return 1
  else
    /bin/rm -f "$AUTHORIZED_KEYS"
    if (( SSH_DIRECTORY_CREATED )); then /bin/rmdir "$HOME/.ssh" 2>/dev/null || true; fi
  fi
  AUTHORIZATION_CHANGED=0
}

on_exit() {
  local status=$?
  trap - EXIT
  if ! restore_authorization; then
    printf '\n%s%s  WARNING: failed to restore %s%s\n' "$BOLD" "$RED" "$AUTHORIZED_KEYS" "$RESET"
    status=1
  fi
  if (( IDENTITY_CREATED )) && (( ! CLEANED_UP )); then
    printf '\n%s%s  Test identity still exists%s\n' "$BOLD" "$YELLOW" "$RESET"
    printf '  Delete it with:\n    /usr/sbin/sc_auth delete-ctk-identity -h %q\n' "${CTK_SHA1:-SHA1}"
    printf '  Its CTK SHA-256 hash is %s\n' "${CTK_SHA256:-unknown}"
    printf '  Temporary directory: %s\n' "$RUN_DIR"
  else
    /bin/rm -rf "$RUN_DIR"
  fi
  (( status == 0 )) || printf '\n  Failed during stage: %s\n' "$CURRENT_STAGE"
  exit "$status"
}
trap on_exit EXIT

resolve_sha1() {
  local json="$RUN_DIR/list-sha1.json" index=0 entry_label found=""
  "$SSHCTL" identity list -t sha1 --json > "$json"
  while entry_label=$(/usr/bin/plutil -extract "identities.$index.label" raw -o - "$json" 2>/dev/null); do
    if [[ "$entry_label" == "$LABEL" ]]; then
      [[ -z "$found" ]] || return 2
      found=$(/usr/bin/plutil -extract "identities.$index.ctkPublicKeyHash" raw -o - "$json")
    fi
    index=$(( index + 1 ))
  done
  [[ -n "$found" ]] || return 1
  printf '%s' "$found"
}

# valid_column — the Valid column sc_auth prints for the test label.
valid_column() {
  local json="$RUN_DIR/list-after.json" index=0 entry_label
  "$SSHCTL" identity list --json > "$json"
  while entry_label=$(/usr/bin/plutil -extract "identities.$index.label" raw -o - "$json" 2>/dev/null); do
    if [[ "$entry_label" == "$LABEL" ]]; then
      /usr/bin/plutil -extract "identities.$index.certificateValid" raw -o - "$json"
      return 0
    fi
    index=$(( index + 1 ))
  done
  return 1
}

measure() {
  local phase="$1" local_var="$2" remote_var="$3" outcome=failed
  if "$SSHCTL" verify local --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" \
      --json > "$RUN_DIR/$phase-local.json" 2>"$RUN_DIR/$phase-local.err"; then
    outcome=passed
  else
    note "$(/usr/bin/tail -n 2 "$RUN_DIR/$phase-local.err")"
  fi
  printf -v "$local_var" '%s' "$outcome"
  outcome=failed
  if "$SSHCTL" verify remote --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" \
      --target "$USER@localhost" --json > "$RUN_DIR/$phase-remote.json" 2>"$RUN_DIR/$phase-remote.err"; then
    outcome=passed
  else
    note "$(/usr/bin/tail -n 2 "$RUN_DIR/$phase-remote.err")"
  fi
  printf -v "$remote_var" '%s' "$outcome"
}

banner "se-sshctl certificate expiry measurement"

# ── preflight ─────────────────────────────────────────────────────────────
CURRENT_STAGE=preflight
stage "Check tools and build"
say "This answers one open question: does an expired X.509 certificate stop"
say "OpenSSH from authenticating with the Secure Enclave key behind it?"
note "Nobody here knows the answer. A 'still works' result is as useful as a break."
[[ "$(/usr/bin/uname -m)" == "arm64" ]] || { warn "Apple silicon is required"; exit 1; }
OPENSSL=""
for candidate in /opt/homebrew/opt/openssl@3/bin/openssl /opt/homebrew/bin/openssl /usr/local/opt/openssl@3/bin/openssl; do
  if [[ -x "$candidate" ]] && "$candidate" x509 -help 2>&1 | /usr/bin/grep -q -- '-not_after'; then
    OPENSSL="$candidate"; break
  fi
done
[[ -n "$OPENSSL" ]] || {
  warn "an OpenSSL 3 binary with -not_after is required to backdate a certificate"
  warn "macOS ships LibreSSL, which cannot set notAfter directly"
  warn "install one with: brew install openssl@3"
  exit 1
}
note "using $OPENSSL ($("$OPENSSL" version))"
(cd "$REPO_ROOT" && /usr/bin/swift build --configuration release)
[[ -x "$SSHCTL" ]] || { warn "release build did not produce se-sshctl"; exit 1; }
DOCTOR_JSON="$RUN_DIR/doctor.json"
"$SSHCTL" doctor --json > "$DOCTOR_JSON"
[[ "$(/usr/bin/plutil -extract provider.appleAnchored raw -o - "$DOCTOR_JSON")" == "true" ]] || {
  warn "the SSH provider is not Apple-anchored"; exit 1;
}
MACOS_VERSION=$(/usr/bin/plutil -extract platform.version raw -o - "$DOCTOR_JSON")
OPENSSH_VERSION=$(/usr/bin/plutil -extract openSSH.version raw -o - "$DOCTOR_JSON")

# ── create ────────────────────────────────────────────────────────────────
CURRENT_STAGE=create
stage "Create a throwaway identity"
warn "A p-256-ne + none identity named $LABEL is created and deleted at the end."
confirm "Create it now?" || exit 0
IDENTITY_CREATED=1
"$SSHCTL" identity create -l "$LABEL" -k p-256-ne -t none --allow-unattended-signing \
  --json > "$RUN_DIR/create.json"
CTK_SHA256=$(/usr/bin/plutil -extract identity.ctkPublicKeyHash raw -o - "$RUN_DIR/create.json")
[[ "$CTK_SHA256" =~ ^[0-9A-Fa-f]{64}$ ]] || { warn "creation returned an invalid hash"; exit 1; }
CTK_SHA1=$(resolve_sha1) || { warn "could not resolve the sc_auth SHA-1 hash"; exit 1; }
"$SSHCTL" install --ctk-sha256 "$CTK_SHA256" --identity-file "$IDENTITY_FILE" \
  --no-passphrase --json > "$RUN_DIR/install.json"
if [[ -f "$AUTHORIZED_KEYS" ]]; then
  AUTHORIZED_KEYS_EXISTED=1
  /bin/cp -fp "$AUTHORIZED_KEYS" "$AUTHORIZED_KEYS_BACKUP"
else
  [[ -d "$HOME/.ssh" ]] || { /bin/mkdir -p "$HOME/.ssh"; /bin/chmod 700 "$HOME/.ssh"; SSH_DIRECTORY_CREATED=1; }
fi
/bin/cat "$IDENTITY_FILE.pub" >> "$AUTHORIZED_KEYS"
/bin/chmod 600 "$AUTHORIZED_KEYS"
AUTHORIZATION_CHANGED=1

# ── baseline ──────────────────────────────────────────────────────────────
CURRENT_STAGE=baseline
stage "Measure with the certificate sc_auth issued"
measure before BEFORE_LOCAL BEFORE_REMOTE
say "local signing:            $BEFORE_LOCAL"
say "localhost authentication: $BEFORE_REMOTE"
[[ "$BEFORE_LOCAL" == "passed" && "$BEFORE_REMOTE" == "passed" ]] || {
  warn "the baseline does not pass, so an expiry result would mean nothing"; exit 1;
}

# ── backdate ──────────────────────────────────────────────────────────────
CURRENT_STAGE=backdate
stage "Issue an already-expired certificate for the same key"
say "The private key never moves. sc_auth makes a CSR for it, a throwaway CA"
say "signs that CSR with notAfter in the past, and sc_auth imports the result."
/usr/sbin/sc_auth create-ctk-csr -h "$CTK_SHA1" -f "$RUN_DIR/request.csr" \
  -N "$LABEL" || { warn "sc_auth could not produce a CSR for this key"; exit 1; }
"$OPENSSL" req -x509 -newkey rsa:2048 -nodes -days 3650 \
  -subj "/CN=se-sshctl throwaway expiry CA" \
  -keyout "$RUN_DIR/ca.key" -out "$RUN_DIR/ca.crt" >/dev/null 2>&1
NOT_BEFORE=$(/bin/date -u -v-10d '+%Y%m%d%H%M%SZ')
NOT_AFTER=$(/bin/date -u -v-1d '+%Y%m%d%H%M%SZ')
"$OPENSSL" x509 -req -in "$RUN_DIR/request.csr" \
  -CA "$RUN_DIR/ca.crt" -CAkey "$RUN_DIR/ca.key" -set_serial 1 \
  -not_before "$NOT_BEFORE" -not_after "$NOT_AFTER" \
  -out "$RUN_DIR/expired.crt" >/dev/null 2>&1 \
  || { warn "could not sign the CSR with a past notAfter"; exit 1; }
note "issued notBefore=$NOT_BEFORE notAfter=$NOT_AFTER"
if /usr/sbin/sc_auth import-ctk-certificate -f "$RUN_DIR/expired.crt"; then
  IMPORT_RESULT=passed
else
  IMPORT_RESULT=failed
  warn "sc_auth refused the expired certificate — that is itself the answer"
  warn "for this half of the question: expiry cannot be reached this way."
fi

# ── after ─────────────────────────────────────────────────────────────────
CURRENT_STAGE=after
stage "Measure again"
if [[ "$IMPORT_RESULT" == "passed" ]]; then
  AFTER_VALID_COLUMN=$(valid_column || printf 'missing')
  note "sc_auth now reports certificateValid=$AFTER_VALID_COLUMN"
  measure after AFTER_LOCAL AFTER_REMOTE
  say "local signing:            $AFTER_LOCAL"
  say "localhost authentication: $AFTER_REMOTE"
else
  note "skipped: the expired certificate was never imported"
fi

# ── reinstall ─────────────────────────────────────────────────────────────
CURRENT_STAGE=reinstall
stage "Download a fresh identity file with the certificate expired"
say "The measurement above used the identity file installed before the swap."
say "That shows an existing file keeps working. It does not show whether"
say "ssh-keygen -K will still hand out a new one once the certificate expired."
if [[ "$IMPORT_RESULT" == "passed" ]]; then
  REINSTALLED="$RUN_DIR/reinstalled"
  if "$SSHCTL" install --ctk-sha256 "$CTK_SHA256" --identity-file "$REINSTALLED" \
      --no-passphrase --json > "$RUN_DIR/reinstall.json" 2>"$RUN_DIR/reinstall.err"; then
    REINSTALL_RESULT=passed
    if "$SSHCTL" verify local --ctk-sha256 "$CTK_SHA256" --identity-file "$REINSTALLED" \
        --json > "$RUN_DIR/reinstall-local.json" 2>"$RUN_DIR/reinstall-local.err"; then
      REINSTALL_LOCAL=passed
    else
      REINSTALL_LOCAL=failed
      note "$(/usr/bin/tail -n 2 "$RUN_DIR/reinstall-local.err")"
    fi
  else
    REINSTALL_RESULT=failed
    note "$(/usr/bin/tail -n 3 "$RUN_DIR/reinstall.err")"
  fi
  say "identity-file download:   $REINSTALL_RESULT"
  say "signing with the new file: $REINSTALL_LOCAL"
else
  note "skipped: the expired certificate was never imported"
fi

# ── record ────────────────────────────────────────────────────────────────
CURRENT_STAGE=record
stage "Write the result and clean up"
{
  printf '\n## Certificate expiry measurement — %s\n\n' "$(/bin/date -u '+%Y-%m-%d')"
  printf '```text\n'
  printf 'macOS:    %s\n' "$MACOS_VERSION"
  printf 'OpenSSH:  %s\n' "$OPENSSH_VERSION"
  printf 'source:   %s\n' "$(cd "$REPO_ROOT" && /usr/bin/git rev-parse HEAD)"
  printf 'notAfter: %s (in the past)\n' "$NOT_AFTER"
  printf '```\n\n'
  printf '| Certificate | sc_auth Valid | local signing | localhost authentication |\n'
  printf '| --- | --- | --- | --- |\n'
  printf '| as issued by sc_auth | YES | %s | %s |\n' "$BEFORE_LOCAL" "$BEFORE_REMOTE"
  printf '| backdated, re-imported | %s | %s | %s |\n' \
    "$AFTER_VALID_COLUMN" "$AFTER_LOCAL" "$AFTER_REMOTE"
  printf '\nWith the certificate expired:\n\n'
  printf -- '- import-ctk-certificate: %s\n' "$IMPORT_RESULT"
  printf -- '- fresh identity-file download (ssh-keygen -K): %s\n' "$REINSTALL_RESULT"
  printf -- '- signing with that freshly downloaded file: %s\n' "$REINSTALL_LOCAL"
  printf '\nThe certificate was replaced through create-ctk-csr and\n'
  printf 'import-ctk-certificate, so the non-exportable private key is unchanged\n'
  printf 'between the two rows.\n'
} >> "$REPORT_TARGET"
say "Appended to $REPORT_TARGET."
warn "The next action permanently deletes only the test identity named $LABEL."
confirm "Delete it and restore $AUTHORIZED_KEYS now?" || { warn "cleanup skipped"; exit 1; }
# The tool's own deletion, so the verification records this run created are
# cleared with the key rather than left pointing at nothing.
"$SSHCTL" identity delete --ctk-sha256 "$CTK_SHA256" --confirm "$CTK_SHA256" \
  || { warn "deletion failed"; exit 1; }
restore_authorization || { warn "failed to restore $AUTHORIZED_KEYS"; exit 1; }
IDENTITY_CREATED=0
CLEANED_UP=1
finish
